image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

stages:
  - build-docs
  - deploy-docs

default:
  before_script:
    # See https://github.com/git-lfs/git-lfs/wiki/Installation
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    - apt-get install git-lfs
    - git lfs install

prepare:
  stage: .pre
  only:
    - build-docs-with-gitlab-ci
  script:
    - cargo --version
    - rustc --version

    - if [[ -z "$TAG_STABLE" ]]; then echo "TAG_STABLE must be set!"; exit 1; fi;
    - if [[ -z "$BRANCH_WASM" ]]; then echo "BRANCH_WASM must be set!"; exit 1; fi;

    - if [[ -z "$DOCS_SERVER" ]]; then echo "DOCS_SERVER must be set!"; exit 1; fi;
    - if [[ -z "$DOCS_APP" ]]; then echo "DOCS_APP must be set!"; exit 1; fi;
    - if [[ -z "$BOOK_APP" ]]; then echo "BOOK_APP must be set!"; exit 1; fi;

book:
  stage: build-docs
  only:
    - build-docs-with-gitlab-ci
  cache:
    paths:
      - cargo/
  artifacts:
    untracked: true
  script:
    - cargo install mdbook --no-default-features --features output --vers "^0.3.7"
    - ./cargo/bin/mdbook --version
    - mkdir book-public

    - echo "Building master book..."
    - mkdir book-public/master
    - ./cargo/bin/mdbook build book
    - mv book/book/* book-public/master/
    - rm -rf book/book

    - echo "Building stable book ($TAG_STABLE)..."
    - git checkout $TAG_STABLE
    - mkdir book-public/stable
    - ./cargo/bin/mdbook build book
    - mv book/book/* book-public/stable/
    - rm -rf book/book

    - touch book-public/.static
    - echo "/ amethyst" >> book-public/CHECKS

docs:
  stage: build-docs
  only:
    - build-docs-with-gitlab-ci
  artifacts:
    untracked: true
  cache:
    paths:
      - target/
  script:
    - echo "Installing dependencies..."
    - apt-get update && apt-get install -y libasound2-dev libcurl4-openssl-dev libdw-dev libelf-dev libexpat1-dev libfreetype6-dev libiberty-dev libsdl2-dev libssl-dev libx11-xcb-dev libxcb1-dev && apt-get clean

    - mkdir docs-public

    - echo "Building master docs..."
    - mkdir docs-public/master
    - cargo doc --all --features="animation gltf vulkan"
    - cp -r target/doc/* docs-public/master/

    - echo "Building stable docs ($TAG_STABLE)..."
    - git checkout $TAG_STABLE
    - mkdir docs-public/stable
    - cargo doc --all --features="animation gltf vulkan"
    - cp -r target/doc/* docs-public/stable/

    - touch docs-public/.static
    - echo "/ amethyst" >> docs-public/CHECKS

deploy-docs:
  stage: deploy-docs
  only:
    - build-docs-with-gitlab-ci
  dependencies:
    - docs
    - book
  script:
    - echo "Adding docs deploy SSH key..."

    # See https://docs.gitlab.com/ee/ci/ssh_keys/
    - eval $(ssh-agent -s)
    - echo "$DOCS_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "Deploying docs..."
    - tar c build-docs | ssh dokku@${DOCS_SERVER} tar:in ${DOCS_APP}

    - echo "Deploying book..."
    - tar c build-book | ssh dokku@${DOCS_SERVER} tar:in ${BOOK_APP}