[hooks]
pre-commit = [
    "cargo check --workspace --features empty,optional",
    "cargo fix --workspace --features empty,optional",
    "cargo +nightly clippy -Z unstable-options --workspace --features empty,optional --fix",
    "cargo +nightly fmt --all",
]
pre-push = ["cargo test --all-targets --workspace --features empty,optional"]

[logging]
verbose = true
