# Test suite must pass on GitHub Actions before merging into `master`.
status = [
    "tests (macos-latest, stable)",
    "tests (macos-latest, beta)",
    "tests (macos-latest, nightly)",
    "tests (windows-latest, stable)",
    "tests (windows-latest, beta)",
    "tests (windows-latest, nightly)",
    "tests (ubuntu-latest, stable)",
    "tests (ubuntu-latest, beta)",
    "tests (ubuntu-latest, nightly)",
]

# Do not allow pull requests with these labels to be merged.
block_labels = [
    "status: blocked",
    "status: discussing",
    "status: in progress",
    "status: needs triage"
]

# This feature is rarely useful and more often problematic, so we turn it off.
delete_merged_branches = false

# Increase timeout to 5 hours as the default timeout is too short for our build
timeout_sec = 18000

[committer]
name = "amethyst-bors"
email = "bors@amethyst-engine.org"
