[package]
name = "amethyst_assets"
version = "0.15.3"
authors = [
    "torkleyy <torkleyy@gmail.com>",
    "Amethyst Foundation <contact@amethyst.rs>",
]
readme = "README.md"
edition = "2018"
description = """
Asynchronous asset management for games.
"""
exclude = ["examples/*"]
license = "MIT/Apache-2.0"
keywords = ["game", "asset", "resource", "management", "amethyst"]
categories = ["filesystem"]

documentation = "https://docs.amethyst.rs/stable/amethyst_assets/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

[dependencies]
amethyst_core = { path = "../amethyst_core", version = "0.15.3" }
#amethyst_derive = { path = "../amethyst_derive", version = "0.15.3" }
amethyst_error = { path = "../amethyst_error", version = "0.15.3" }
crossbeam-queue = "0.1.2"
derivative = "2.1.1"
crossbeam-channel = "0.3"
derive-new = "0.5"
fnv = "1"
log = "0.4.6"
parking_lot = "0.10"
rayon = "1.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
ron = "0.5"
thread_profiler = { version = "0.3", optional = true }
err-derive = "0.2.3"
objekt = "0.1.2"
erased-serde = "0.3.9"
inventory = "0.1.5"
lazy_static = "1.4"
# atelier-core = "0.1"
# atelier-loader = "0.1"
# atelier-importer = "0.1"
# atelier-daemon = { version = "0.1", default-features = false }
atelier-core = { git = "https://github.com/jlowry/atelier-assets.git", branch = "make_daemon_constructable", features = ["serde-1", "type_uuid"] }
atelier-loader = { git = "https://github.com/jlowry/atelier-assets.git", branch = "make_daemon_constructable", features = ["default", "asset_uuid_macro"] }
atelier-importer = { git = "https://github.com/jlowry/atelier-assets.git", branch = "make_daemon_constructable", features = ["serde_importers"] }
atelier-daemon = { git = "https://github.com/jlowry/atelier-assets.git", branch = "make_daemon_constructable" }
uuid = { version = "0.8", features = ["v4"] }
bincode = "1.1"
type-uuid = "0.1"
futures-executor = { version = "0.3", default-features = false }
legion-transaction = "0.1"
legion-prefab = "0.1"
prefab-format = "0.1"

# [patch.crates-io]
# legion-transaction = { git = "https://github.com/jlowry/prefab", branch = "serde-diff-0.4" }
# legion-prefab = { git = "https://github.com/jlowry/prefab", branch = "serde-diff-0.4" }
# prefab-format = { git = "https://github.com/jlowry/prefab", branch = "serde-diff-0.4" }

[dev-dependencies]
serde_json = "1"
fern = { version = "0.6.0", features = ["colored"] }
serde-diff = "0.4"

# I want this to be an optional dev-dependency, but it's not possible :(
# atelier-daemon = { git = "https://github.com/jlowry/atelier-assets.git", branch = "make_daemon_constructable", default-features = false }

[features]
profiler = ["thread_profiler/thread_profiler"]
json = ["serde_json"]
